In [2]:
import pandas as pd

data = pd.read_csv('de_cc_data.txt', sep=",", header=None, names=['id', 'prescriber_last_name', 'prescriber_first_name', 'drug_name', 'drug_cost'])
data.describe()

C:\Users\lei\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (0,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,prescriber_last_name,prescriber_first_name,drug_name,drug_cost
count,24525860,24525411,24525652,24525860,24525860.0
unique,866572,214240,63608,2750,2453361.0
top,1124047717,SMITH,JOHN,HYDROCODONE-ACETAMINOPHEN,48.0
freq,559,135451,530457,306651,2944.0

In [3]:
data.count()

id                       24525860
prescriber_last_name     24525411
prescriber_first_name    24525652
drug_name                24525860
drug_cost                24525860
dtype: int64

In [4]:
data.head()

,id,prescriber_last_name,prescriber_first_name,drug_name,drug_cost
0,id,prescriber_last_name,prescriber_first_name,drug_name,drug_cost
1,1952310666,A'BODJEDI,ENENGE,ALPRAZOLAM,1964.49
2,1952310666,A'BODJEDI,ENENGE,AMANTADINE,1129.94
3,1952310666,A'BODJEDI,ENENGE,AMBIEN,4792.29
4,1952310666,A'BODJEDI,ENENGE,AMBIEN CR,4792.29

In [5]:
data.head(50)

,id,prescriber_last_name,prescriber_first_name,drug_name,drug_cost
0,id,prescriber_last_name,prescriber_first_name,drug_name,drug_cost
1,1952310666,A'BODJEDI,ENENGE,ALPRAZOLAM,1964.49
2,1952310666,A'BODJEDI,ENENGE,AMANTADINE,1129.94
3,1952310666,A'BODJEDI,ENENGE,AMBIEN,4792.29
4,1952310666,A'BODJEDI,ENENGE,AMBIEN CR,4792.29
5,1952310666,A'BODJEDI,ENENGE,AMITRIPTYLINE HCL,692.78
6,1952310666,A'BODJEDI,ENENGE,ARIPIPRAZOLE,8374.44
7,1952310666,A'BODJEDI,ENENGE,BENZTROPINE MESYLATE,1868.72
8,1952310666,A'BODJEDI,ENENGE,BUPROPION XL,3111.04
9,1952310666,A'BODJEDI,ENENGE,BUSPIRONE HCL,837.7
10,1952310666,A'BODJEDI,ENENGE,CHLORPROMAZINE HCL,26826.62
11,1952310666,A'BODJEDI,ENENGE,CITALOPRAM HBR,422.3
12,1952310666,A'BODJEDI,ENENGE,CLOMIPRAMINE HCL,8886.79
13,1952310666,A'BODJEDI,ENENGE,CLONAZEPAM,1848.88
14,1952310666,A'BODJEDI,ENENGE,CLOZAPINE,6275.67
15,1952310666,A'BODJEDI,ENENGE,DESIPRAMINE HCL,1210.35
16,1952310666,A'BODJEDI,ENENGE,DEXTROAMPHETAMINE-AMPHETAMINE,1728.4
17,1952310666,A'BODJEDI,ENENGE,DIAZEPAM,662.87
18,1952310666,A'BODJEDI,ENENGE,DIVALPROEX SODIUM,1083.57
19,1952310666,A'BODJEDI,ENENGE,DIVALPROEX SODIUM ER,14448.59
20,1952310666,A'BODJEDI,ENENGE,DONEPEZIL HCL,115.39
21,1952310666,A'BODJEDI,ENENGE,DOXEPIN HCL,270.66
22,1952310666,A'BODJEDI,ENENGE,DULOXETINE HCL,1214.05
23,1952310666,A'BODJEDI,ENENGE,ESCITALOPRAM OXALATE,902.52
24,1952310666,A'BODJEDI,ENENGE,FANAPT,11967.55
25,1952310666,A'BODJEDI,ENENGE,FETZIMA,12320.7
26,1952310666,A'BODJEDI,ENENGE,FLUOXETINE HCL,933.88
27,1952310666,A'BODJEDI,ENENGE,FLUPHENAZINE DECANOATE,4736.79
28,1952310666,A'BODJEDI,ENENGE,FLUPHENAZINE HCL,1323.9
29,1952310666,A'BODJEDI,ENENGE,FLUVOXAMINE MALEATE,192.64
30,1952310666,A'BODJEDI,ENENGE,GABAPENTIN,1807.16
31,1952310666,A'BODJEDI,ENENGE,HALOPERIDOL,830.99
32,1952310666,A'BODJEDI,ENENGE,HYDROXYZINE HCL,945.5
33,1952310666,A'BODJEDI,ENENGE,INVEGA SUSTENNA,75345.68
34,1952310666,A'BODJEDI,ENENGE,LAMOTRIGINE,331.39
35,1952310666,A'BODJEDI,ENENGE,LATUDA,104040.59
36,1952310666,A'BODJEDI,ENENGE,LITHIUM CARBONATE,114.22
37,1952310666,A'BODJEDI,ENENGE,LITHIUM CARBONATE ER,371.0
38,1952310666,A'BODJEDI,ENENGE,LORAZEPAM,1470.02
39,1952310666,A'BODJEDI,ENENGE,MIRTAZAPINE,521.88
40,1952310666,A'BODJEDI,ENENGE,NORTRIPTYLINE HCL,88.47
41,1952310666,A'BODJEDI,ENENGE,OLANZAPINE,4020.95
42,1952310666,A'BODJEDI,ENENGE,OLANZAPINE ODT,618.13
43,1952310666,A'BODJEDI,ENENGE,OLEPTRO ER,2919.43
44,1952310666,A'BODJEDI,ENENGE,OXCARBAZEPINE,687.17
45,1952310666,A'BODJEDI,ENENGE,PAROXETINE HCL,923.73
46,1952310666,A'BODJEDI,ENENGE,PERPHENAZINE,2891.51
47,1952310666,A'BODJEDI,ENENGE,PRISTIQ ER,7056.32
48,1952310666,A'BODJEDI,ENENGE,QUETIAPINE FUMARATE,5473.43
49,1952310666,A'BODJEDI,ENENGE,RISPERIDONE,4419.71

In [6]:
data.tail(50)

,id,prescriber_last_name,prescriber_first_name,drug_name,drug_cost
24525810,1609070531,ZYZNIEWSKI,WENDY,NOVOLIN R,1816.82
24525811,1609070531,ZYZNIEWSKI,WENDY,OMEPRAZOLE,640
24525812,1609070531,ZYZNIEWSKI,WENDY,OXYBUTYNIN CHLORIDE ER,1093.68
24525813,1609070531,ZYZNIEWSKI,WENDY,OXYCODONE HCL,1245.29
24525814,1609070531,ZYZNIEWSKI,WENDY,PANTOPRAZOLE SODIUM,227.42
24525815,1609070531,ZYZNIEWSKI,WENDY,PAROXETINE HCL,113.9
24525816,1609070531,ZYZNIEWSKI,WENDY,PRAVASTATIN SODIUM,1634.09
24525817,1609070531,ZYZNIEWSKI,WENDY,PROAIR HFA,1168.41
24525818,1609070531,ZYZNIEWSKI,WENDY,RANITIDINE HCL,410.78
24525819,1609070531,ZYZNIEWSKI,WENDY,SERTRALINE HCL,201.94
24525820,1609070531,ZYZNIEWSKI,WENDY,SIMVASTATIN,377.52
24525821,1609070531,ZYZNIEWSKI,WENDY,SPIRONOLACTONE,166.06
24525822,1609070531,ZYZNIEWSKI,WENDY,SULFAMETHOXAZOLE-TRIMETHOPRIM,67.87
24525823,1609070531,ZYZNIEWSKI,WENDY,TOLTERODINE TARTRATE,1322.94
24525824,1609070531,ZYZNIEWSKI,WENDY,TRAMADOL HCL,334.65
24525825,1609070531,ZYZNIEWSKI,WENDY,TRAZODONE HCL,113.45
24525826,1609070531,ZYZNIEWSKI,WENDY,VENLAFAXINE HCL ER,1409.46
24525827,1609070531,ZYZNIEWSKI,WENDY,WARFARIN SODIUM,135.5
24525828,1609070531,ZYZNIEWSKI,WENDY,ZOLPIDEM TARTRATE,195.2
24525829,1124277249,ZZIWA-KABENGE,IRYNE,ACYCLOVIR,974.53
24525830,1124277249,ZZIWA-KABENGE,IRYNE,ATRIPLA,165687
24525831,1124277249,ZZIWA-KABENGE,IRYNE,COMPLERA,41088.8
24525832,1124277249,ZZIWA-KABENGE,IRYNE,EPZICOM,162299
24525833,1124277249,ZZIWA-KABENGE,IRYNE,GABAPENTIN,117.67
24525834,1124277249,ZZIWA-KABENGE,IRYNE,INTELENCE,73487.7
24525835,1124277249,ZZIWA-KABENGE,IRYNE,ISENTRESS,233896
24525836,1124277249,ZZIWA-KABENGE,IRYNE,LAMIVUDINE,3275.9
24525837,1124277249,ZZIWA-KABENGE,IRYNE,LAMIVUDINE HBV,6601.78
24525838,1124277249,ZZIWA-KABENGE,IRYNE,LAMIVUDINE-ZIDOVUDINE,5591.88
24525839,1124277249,ZZIWA-KABENGE,IRYNE,NORVIR,51198.2
24525840,1124277249,ZZIWA-KABENGE,IRYNE,PREZCOBIX,23100.7
24525841,1124277249,ZZIWA-KABENGE,IRYNE,PREZISTA,147401
24525842,1124277249,ZZIWA-KABENGE,IRYNE,REYATAZ,112874
24525843,1124277249,ZZIWA-KABENGE,IRYNE,STRIBILD,171206
24525844,1124277249,ZZIWA-KABENGE,IRYNE,SUSTIVA,38119.8
24525845,1124277249,ZZIWA-KABENGE,IRYNE,TIVICAY,93125.5
24525846,1124277249,ZZIWA-KABENGE,IRYNE,TRIUMEQ,261146
24525847,1124277249,ZZIWA-KABENGE,IRYNE,TRUVADA,148729
24525848,1124277249,ZZIWA-KABENGE,IRYNE,VALACYCLOVIR,1625.31
24525849,1124277249,ZZIWA-KABENGE,IRYNE,ZIDOVUDINE,969.74
24525850,1033160296,ZZIWAMBAZZA,NATHAN,AMOXICILLIN-CLAVULANATE POTASS,210.91
24525851,1033160296,ZZIWAMBAZZA,NATHAN,AZITHROMYCIN,137.96
24525852,1033160296,ZZIWAMBAZZA,NATHAN,CEPHALEXIN,145.41
24525853,1033160296,ZZIWAMBAZZA,NATHAN,CIPROFLOXACIN HCL,126.99
24525854,1033160296,ZZIWAMBAZZA,NATHAN,DOXYCYCLINE HYCLATE,635.8
24525855,1033160296,ZZIWAMBAZZA,NATHAN,HYDROCODONE-ACETAMINOPHEN,395.59
24525856,1033160296,ZZIWAMBAZZA,NATHAN,ONDANSETRON ODT,202.39
24525857,1033160296,ZZIWAMBAZZA,NATHAN,PREDNISONE,146.92
24525858,1033160296,ZZIWAMBAZZA,NATHAN,SULFAMETHOXAZOLE-TRIMETHOPRIM,48
24525859,1033160296,ZZIWAMBAZZA,NATHAN,TRAMADOL HCL,92.08

In [7]:
data.id

0                   id
1           1952310666
2           1952310666
3           1952310666
4           1952310666
5           1952310666
6           1952310666
7           1952310666
8           1952310666
9           1952310666
10          1952310666
11          1952310666
12          1952310666
13          1952310666
14          1952310666
15          1952310666
16          1952310666
17          1952310666
18          1952310666
19          1952310666
20          1952310666
21          1952310666
22          1952310666
23          1952310666
24          1952310666
25          1952310666
26          1952310666
27          1952310666
28          1952310666
29          1952310666
               ...
24525830    1124277249
24525831    1124277249
24525832    1124277249
24525833    1124277249
24525834    1124277249
24525835    1124277249
24525836    1124277249
24525837    1124277249
24525838    1124277249
24525839    1124277249
24525840    1124277249
24525841    1124277249
24525842    1124277249
24525843    1124277249
24525844    1124277249
24525845    1124277249
24525846    1124277249
24525847    1124277249
24525848    1124277249
24525849    1124277249
24525850    1033160296
24525851    1033160296
24525852    1033160296
24525853    1033160296
24525854    1033160296
24525855    1033160296
24525856    1033160296
24525857    1033160296
24525858    1033160296
24525859    1033160296
Name: id, Length: 24525860, dtype: object

In [8]:
data['id'].count()

24525860

In [9]:
data.groupby('id').count()

            prescriber_last_name  prescriber_first_name  drug_name  drug_cost
id
1003000126                    21                     21         21         21
1003000142                    20                     20         20         20
1003000167                     2                      2          2          2
1003000282                     1                      1          1          1
1003000407                    35                     35         35         35
1003000480                     1                      1          1          1
1003000522                   107                    107        107        107
1003000530                   127                    127        127        127
1003000597                     4                      4          4          4
1003000720                     4                      4          4          4
1003000753                     2                      2          2          2
1003000902                   100                    100        100        100
1003000936                    30                     30         30         30
1003001017                     8                      8          8          8
1003001132                     4                      4          4          4
1003001207                     1                      1          1          1
1003001256                     1                      1          1          1
1003001363                    30                     30         30         30
1003001371                    10                     10         10         10
1003001462                     4                      4          4          4
1003001645                    15                     15         15         15
1003001785                     5                      5          5          5
1003001868                     1                      1          1          1
1003001884                    68                     68         68         68
1003002049                    28                     28         28         28
1003002072                    20                     20         20         20
1003002312                    83                     83         83         83
1003002320                     4                      4          4          4
1003002379                     1                      1          1          1
1003002510                     1                      1          1          1
...                          ...                    ...        ...        ...
1992195101                     1                      1          1          1
1992714851                    23                     23         23         23
1992717854                    14                     14         14         14
1992723654                     4                      4          4          4
1992732168                    13                     13         13         13
1992734792                     4                      4          4          4
1992740625                     7                      7          7          7
1992741912                     2                      2          2          2
1992754832                    94                     94         94         94
1992780688                    17                     17         17         17
1992781173                     6                      6          6          6
1992793418                    82                     82         82         82
1992798797                    37                     37         37         37
1992803985                   114                    114        114        114
1992811418                     8                      8          8          8
1992817456                    24                     24         24         24
1992830152                     7                      7          7          7
1992848741                    14                     14         14         14
1992854707                    34                     34         34         34
1992865190                     4                      4          4          4
1992873418                     4                      4          4          4
1992883532                     1                      1          1          1
1992899470                    39                     39         39         39
1992926448                     2                      2          2          2
1992927701                     2                      2          2          2
1992927958                     1                      1          1          1
1992970560                     4                      4          4          4
1992982052                   115                    115        115        115
1992988026                     8                      8          8          8
id                             1                      1          1          1

[866572 rows x 4 columns]